### ISSUE TITLE
Create NServiceBus.Cloudwatch package

### ISSUE THREAD

**Issue by ahofman** [Particular/NServiceBus.AmazonSQS#28] opened 2015-01-15 02:23 UTC

**Comment by ahofman** [comment] 2015-01-18 22:23
Can be done with the CloudWatch API. Powershell samples here: https://aws.amazon.com/code/7932034889155460

This is probably best done as a separate package, so that users can have the option to use cloudwatch with other transports

**Comment by mauroservienti** [comment] 2019-05-14 13:03
Closing as duplicate of https://github.com/Particular/NServiceBus.AmazonSQS/issues/244

**Closed by mauroservienti** 2019-05-14 13:03 UTC
Labels: enhancement
