### ISSUE TITLE
Interest in using Amazon SNS to offer native broker capability?

### ISSUE THREAD

**Issue by chrissimon-au** [Particular/NServiceBus.AmazonSQS#46] opened 2015-12-07 22:36 UTC
NServiceBus with Azure or RabbitMQ transport does not rely on persistent storage for subscription data, rather relying on the broker capability to manage subscriptions.

In AWS-land, SNS seems like the natural service to offer equivalent capability.  A rough outline of behaviour:
- When detecting event messages, check for existence of/create an SNS topic per event
- When subscribing, rather than sending a subscribe message to the 'owner' endpoint, subscribe the subscriber's input-queue to the SNS topic.

Is this something that you guys have already been thinking about?

**Comment by ahofman** [comment] 2016-02-01 03:14
Thanks @chrissimon-au for your great suggestion! This isn't something I've considered yet, but your rough outline appears to be a great fit. 

I unfortunately don't get a great deal of time to work on this plugin at the moment - feel free to create a PR and have a go at building it yourself if you want. If you decide to do so, please assign yourself to this issue (and if I ever do get the time to implement this, I'll do the same). 

(please forgive the lateness of my reply).

**Comment by chrissimon-au** [comment] 2016-02-01 06:08
Hi @ahofman - no problems, I know how it gets!

We are working on a project right now where this might be very useful - will let you know if I get a chance to work on it!

**Comment by ahofman** [comment] 2016-02-01 21:26
A few questions about your project to help me prioritise this work:

1. What kind of timelines are you looking at for your project? i.e., when would you need this feature implemented?
2. If this feature wasn't implemented, would it be a killer for your project? i.e., would you have to use a different transport?

**Comment by chrissimon-au** [comment] 2016-02-01 22:58
Hi Adrian,

Thanks for following up!  Our project is in play this year - we are likely to have to launch (MVP) in the near future (next few months) - the absence of this certainly wouldn't be a killer for the project - we'd stick with SQS transport and traditional persistence based subscriptions.

If we get a chance to implement SNS subscriptions (or you do) we'd likely switch to that after launch though, as I see a number of advantages into the future (including non NServiceBus subscribers, and auditing all published events even if no subscribers...)

Cheers,
Chris.

**Comment by biddlem** [comment] 2020-01-17 14:52
Is there any traction on this feature yet?  This would be extremely helpful for the exact reasons that @chrissimon-au  mentioned.

**Comment by mauroservienti** [comment] 2020-01-21 08:31
Hi @biddlem. We're working on providing support for "_native_" pub/sub for the SQS transport without the need for SNS. The goal is to allow users to use the transport without the need for external subscription storage and, at the same time, without the need to use another service, which means more costs, more moving parts, and more configuration.

This effort has been going on for a while, and we already introduced this new mode in other transport; SQS is next in line. SNS is still on our radar, though. We'd like to know if there is any specific use case you're interested in that can be satisfied by SNS and is not strictly related to pub/sub without subscription storage.

**Comment by biddlem** [comment] 2020-01-28 20:59
@mauroservienti, my main use case is for non-NServiceBus subscribers to be able to be receive the events.

**Comment by mauroservienti** [comment] 2020-01-29 14:27
@biddlem thanks, that makes a lot of sense.

Basically the issue with our "_native_/no-SNS" pub/sub implementation is that it works for NServiceBus endpoints only, and if there is a native integration scenario an endpoint that is not using NServiceBus won't be able to subscribe unless some magic is put in place.

I'll bring this to the attention of the relevant group for further analysis and consideration.

**Comment by chrissimon-au** [comment] 2020-01-29 21:27
Thanks for the update @mauroservienti.  Are you able to share details on how the native subscription mechanism would work?  From a brief review, I think with the SQL transport, it leverages the fact that the SQL Transport has access to a shared database (for the queue tables) to store subscriptions in a shared subscription table.  With SQS transport, not all endpoints will necessarily have access to a shared database - so where will the subscription data be durably persisted?

AWS has designed SNS and SQS to work together natively - SQS for queueing, and SNS for notifications, including built-in subscription management - they seem like a friendly pairing, and I'm not sure I understand the perspective that "SQS-Only" is more 'native' than SQS+SNS, which is a very "AWS-Native" combination? The transport is already using SQS + S3, so I think it should actually be considered an 'AWS transport' rather than purely an 'SQS transport' - and from that perspective, adding SNS to the mix doesn't seem to be too controversial?

That said, I acknowledge that this is a superficial analysis - your team is working much more closely with all this, and I generally trust Particular's judgement in these matters!

**Comment by mauroservienti** [comment] 2020-02-05 17:07
@chrissimon-au we are currently discussing a few options, such as:

- using S3 as a central storage
- using one SQS queue per event type as a storage
- using one single SQS queue

And maybe a few more variations characterized by small differences. We just had a call and we basically started evaluating SNS (again) as another option on the table.

From our perspective, a thing that is truly important is the migration path: we want to enable customers to gradually migrate a system from the current pub/sub implementation to a different one in the simplest possible way and possibly in a gradual way without the need to upgrade all the endpoints at once. We use to do this using a sort of feature in NServiceBus Core called "subscriptions hybrid mode" that allows a publisher to use the old message-based pub/sub and the new one at the same time.

If we have full control of both pub/sub modes, as it happens in SqlTransport we can also guarantee message deduplication, because the scenario could be that subscribers are not yet capable of understanding the new style and will start receiving events twice.

We're not sure yet if this could happen combining SQS and SNS, though. If we were to use SNS this deduplication while in hybrid mode is much more difficult, might be even impossible for publishers.

@chrissimon-au @biddlem thoughts? Would possible message duplication be a problem at the subscriber level?

**Comment by chrissimon-au** [comment] 2020-02-06 10:18
Yes, possible message duplication would not be great - however wouldn't the Outbox prevent that?  Or is the issue message Id management?

In terms of progressive upgrades, I think it could work if endpoints in 'hybrid' mode assume that they always publish via SNS, and so take responsibility for wiring up SNS->SQS even when their subscribers are in the old mode.   (In comparison, normally they would only wire up SNS->SQS for the events _they_ are subscribing to).

They would have to do two things:
1. when subscribing, wire up SNS->SQS (this would be 'normal' in an SNS-world) AND send subscribe messages (just in case the publisher they're subscribing to is in the old mode), and
2. on receipt of a subscribe message, wire up SNS->SQS to the queue of the subscriber (normally, in an SNS-world, this would be done by the subscriber, so there would be no 'subscribe' message).

Consider a partially upgraded system:
* endpointA1 and endpointA2 know how to use SNS->SQS and are in 'hybrid mode'
* endpointB1 and endpointB2 are still using a private subscriptions table.

## endpointA1 subscribes to an endpointB1 event:

1. on startup, endpointA1 attempts to subscribe its queue to the event's topic, creating the topic if it doesn't exist yet
2. endpointA1 sends a 'subscribe' message to endpointB1 ('hybrid mode' only)
3. endpointB1 receives the subscribe message and stores the subscription
4. endopintB1 publishes the event, consults its subscription table, and sends the event directly to endpointA queue

## endpointB1 subscribes to an endpointA1 event:

1. on startup, endpointA1 creates an SNS topic for each of its own events (if they don't exist yet)
2. endpointB1 sends a 'subscribe' message to endpointA1 (default existing functionality)
3. endpointA1 receives the message, and subscribes endpointB1 queue to its event's SNS topic ('hybrid mode' only)
4. endpointA1 publishes the event to the SNS topic, which distributes to endpointB1 queue

## endpointA1 subscribes to an endpointA2 event:

1. on startup, endpointA1 attempts to subscribes its queue to the event's topic, creating the topic if it doesn't exist yet
2. on startup, endpointA2 creates an SNS topic for each of its own events (if they don't exist yet)
2. endpointA1 sends a 'subscribe' message to endpointA2 ('hybrid mode' only)
3. endpointA2 receives the subscribe message and attempts to create the SNS topic and subscription - but sees they already exist from step 1 so nothing changes
4. endpointA2 publishes the message via SNS and SNS distributes to the endpointA1 queue

## endpointB1 subscribes to an endpointB2 event

1. This follows existing subscription and publishing mechanism


The above should allow endpoints to be upgraded one by one (as long as new endpoints are in hybrid mode) and once all endpoints are upgraded, all could disable hybrid mode progressively as well.

If hybrid mode was disabled, the main difference is that received subscribe messages would be discarded (perhaps log a warning) and there would be no need to send subscribe messages on startup.

**Comment by mauroservienti** [comment] 2020-02-06 13:55
> Yes, possible message duplication would not be great - however wouldn't the Outbox prevent that? Or is the issue message Id management?

Yes, Outbox will dedup in this case. So if Outbox can be enabled it solves the problem.

Thanks for all the details. We're continuing our investigation. We'll post updates to this issue as we have more to share.

**Comment by danielmarbach** [comment] 2020-02-10 14:57
@chrissimon-au we are currently thinking about how to setup the topology with SNS and would like your input on "multiple inheritance"

Let's say we have the following message

```
class MyEvent : IEvent, IMessage, IMyCustomEvent
```

and we would map to SNS topics like

 - MyEvent
 - IEvent
 - IMessage
 - IMyCustomEvent
 - object

the publisher would do

```
await context.Publish(new MyEvent());
```

Given a subscriber with two handlers like

- IHandleMessage<IMyCustomEvent>
- IHandleMessage<IEvent>

it means there will be two subscriptions to two topics and therefore both handlers would be invoked twice. The reason is that a copy of the message would go to the topic representing `IMyCustomEvent` and one to the topic representing `IEvent` and the subscribers pipeline would execute locally the handlers.

Is message inheritance something that in your view has to be supported without receiving duplicate invocations or is it OK if duplicate invocation is documented as a caveat of an SNS based solution?

**Comment by chrissimon-au** [comment] 2020-02-11 02:00
@danielmarbach , we don't use message inheritance often, but we have used occasionally.  I think generally it would be best to avoid duplicate handling - I suspect it's likely to cause a lot of confusion.  

One thought about how to avoid it is to use the same message id for the copy of the message sent to each SNS topic - the Outbox on the endpoint receiving the message should deduplicate - each handler will get invoked for the first message that is received (within a single transaction, which is NSB norm, I think?) and then the second copy received will be discarded by the outbox

The Outbox is a requirement of the transport already I believe?

I'm not sure what NSB's default policy is regarding message IDs of events though - if multiple subscribers handle the same message ID does that cause problems further down the line with auditing and error tracking?

**Comment by mauroservienti** [comment] 2020-02-11 06:12
Thanks for the feedback @chrissimon-au. Yes all messages will have the same message ID because they are the same message. And yes in this case Outbox is a solution, even if it has its own caveats. The problem is that handlers will be invoked in the majority of cases and then rolled back, which means that if they have side effects (e.g. outgoing http requests) it’ll be hard to design them. We’re brainstorming other options in the meantime to circumvent the issue.

**Comment by chrissimon-au** [comment] 2020-02-11 06:41
I suspect this is already on your radar, but given that [unrestricted native deferral](https://docs.particular.net/transports/sqs/delayed-delivery) requires FIFO queues there is a precedence for requiring FIFO queues for particular situations - specifically to take advantage of [native deduplication](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/SQSDeveloperGuide/using-messagededuplicationid-property.html)

You could adopt a similar practice:
* if you are not using message inheritance, no need to use FIFO queues
* if you are using message inheritance, you need FIFO queues to enable native de-duplication

It's a similar structure to:
* if you are not using native deferral, no need to use FIFO queues
* if you are using native deferral, you need FIFO queues to enable native deduplication

In my view that would be an acceptable compromise.

(for what it's worth, we never migrated to FIFO queues because we had already migrated to Hangfire for long timeout delays before FIFO queues were available in our region, but they are available now, and we would probably adopt them if it allowed SNS publishing support, and as a result may be able to revert to nservice bus timeouts and retire our use of hangfire...)

**Comment by danielmarbach** [comment] 2020-02-11 07:20
@chrissimon-au yep we were thinking about the following

By default do not require FIFO queues but if you have inheritance allowing customers to opt-in for an additional FIFO queue that belongs to the endpoint. In that mode the SNS subscriptions would be rewired to the FIFO queue. The idea of having an additional queue instead of making the mean one a FIFO queue comes from the fact that when the main input queue becomes a FIFO queue the sender needs to know that fact in the routing table which then spreads this obviously internal choice across the systems routing information

**Comment by jmenziessmith** [comment] 2020-02-29 16:50
I'm also interested in using SNS as a means to enable non NServiceBus systems to subscribe to events. We may be able to help out with any development or testing.

**Comment by mauroservienti** [comment] 2020-03-04 09:34
Quick update on the status of this issue. We've analyzed different options to implement pub/sub using SNS and defined a plan to move forward.

The idea is to have a dedicated topic per event type, similar to what RabbitMQ does. Publishers will publish to a specific topic that matches the event type, and subscribers will set up SNS subscriptions to bind a topic to their input queue based on the events registered in the `MessageMetadataRegistry`. The difference between SNS and RabbitMQ is that SNS topics can't be subscribed to other topics, so the publisher has to explicitly publish to all the topics in the event's inheritance hierarchy.

This topology, called `topic-per-message-type`, comes with the side effect of duplicates at the subscriber. We decided to avoid using FIFO queues top handle that and instead implement a strategy at the subscriber endpoint.

We'll share more details as we move forward with the implementation steps, that should happen soon.

**Comment by mauroservienti** [comment] 2020-03-31 14:52
@chrissimon-au @jmenziessmith @biddlem and @ahofman we're in the process of implementing SNS support, preview bits in #426. We'd like to have your input on the way message inheritance and polymorphic dispatch will be implemented and supported in the new version of the transport.

Please have a look at #430 and post your comments there. We're actively working on this so we have limited time for this RFC process, the PR will be open for comments until Thursday, April 2 - 1 PM CEST.

**Comment by danielmarbach** [comment] 2020-04-27 10:24
We have released support for SNS. The transport can be run in a hybrid mode for a transition period. More details in the announcement

https://discuss.particular.net/t/nservicebus-amazonsqs-5-0-major-release-available/1773

Thank you all for the great input and last but not least your patience.

**Closed by danielmarbach** 2020-04-27 10:24 UTC
Labels: Improvement, candidate-for-next-release
