### ISSUE TITLE
Gateway messages with duplicate ids fail to receive from SQS

### ISSUE THREAD

**Issue by chrisbednarski** [Particular/NServiceBus.AmazonSQS#49] opened 2016-07-28 06:44 UTC
Tested on NSB 4.7.8

```
Bus.SendToSites(new[] { "SiteA", "SiteB" }, new MyRequest());
```

```
NServiceBus.Unicast.Transport.TransportReceiver [(null)] - Failed to process message
Amazon.S3.AmazonS3Exception: The specified key does not exist. ---> Amazon.Runtime.Internal.HttpErrorResponseException: The remote server returned an error: (404) Not Found. ---> System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at Amazon.Runtime.Internal.HttpRequest.GetResponse() in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\HttpHandler\HttpWebRequestFactory.cs:line 106
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpRequest.GetResponse() in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\HttpHandler\HttpWebRequestFactory.cs:line 118
   at Amazon.Runtime.Internal.HttpHandler`1.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\HttpHandler\HttpHandler.cs:line 84
   at Amazon.Runtime.Internal.RedirectHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\Handlers\RedirectHandler.cs:line 41
   at Amazon.Runtime.Internal.Unmarshaller.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\Handlers\Unmarshaller.cs:line 50
   at Amazon.S3.Internal.AmazonS3ResponseHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet35\Amazon.S3\Internal\AmazonS3ResponseHandler.cs:line 42
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 70
   --- End of inner exception stack trace ---
   at Amazon.Runtime.Internal.HttpErrorResponseExceptionHandler.HandleException(IExecutionContext executionContext, HttpErrorResponseException exception) in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\ErrorHandler\HttpErrorResponseExceptionHandler.cs:line 60
   at Amazon.Runtime.Internal.ErrorHandler.ProcessException(IExecutionContext executionContext, Exception exception) in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 202
   at Amazon.Runtime.Internal.ErrorHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\ErrorHandler\ErrorHandler.cs:line 76
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 46
   at Amazon.Runtime.Internal.RetryHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\RetryHandler\RetryHandler.cs:line 88
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 46
   at Amazon.Runtime.Internal.CallbackHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\Handlers\CallbackHandler.cs:line 46
   at Amazon.S3.Internal.AmazonS3ExceptionHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet35\Amazon.S3\Internal\AmazonS3ExceptionHandler.cs:line 39
   at Amazon.Runtime.Internal.ErrorCallbackHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\Handlers\ErrorCallbackHandler.cs:line 44
   at Amazon.Runtime.Internal.MetricsHandler.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\Handlers\MetricsHandler.cs:line 40
   at Amazon.Runtime.Internal.RuntimePipeline.InvokeSync(IExecutionContext executionContext) in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\Pipeline\RuntimePipeline.cs:line 136
   at Amazon.Runtime.AmazonServiceClient.Invoke[TRequest,TResponse](TRequest request, IMarshaller`2 marshaller, ResponseUnmarshaller unmarshaller) in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet35\Amazon.Runtime\AmazonServiceClient.cs:line 117
   at Amazon.S3.AmazonS3Client.GetObject(GetObjectRequest request) in d:\Jenkins\jobs\build-sdk-v2\workspace\sdk\src\AWSSDK_DotNet45\Amazon.S3\AmazonS3Client.cs:line 1541
   at NServiceBus.SQS.SqsMessageExtensions.ToTransportMessage(SqsTransportMessage sqsTransportMessage, IAmazonS3 amazonS3, SqsConnectionConfiguration connectionConfiguration) in Extensions\SqsMessageExtensions.cs:line 11
   at NServiceBus.Transports.SQS.SqsDequeueStrategy.ConsumeMessages() in SqsDequeueStrategy.cs:line 109
```

Gateway messages are [cloned](https://github.com/Particular/NServiceBus.Gateway/blob/develop/src/NServiceBus.Gateway/Sending/GatewaySendBehavior.cs#L45) and re-sent locally when sent to multiple gateway destinations. This process (unfortunately?) keeps message ids identical for each cloned message. 

The message id is used by SQS transport as [the key](https://github.com/ahofman/NServiceBus.AmazonSQS/blob/master/src/NServiceBus.AmazonSQS/SqsQueueSender.cs#L38) into the S3 bucket

Data in S3 bucket is deleted after 1st message is processed, corrupting the other cloned messages

Use id of [SqsTransportMessage](https://github.com/ahofman/NServiceBus.AmazonSQS/blob/master/src/NServiceBus.AmazonSQS/SqsQueueSender.cs#L29)?

**Comment by ahofman** [comment] 2017-04-20 02:49
Thanks @chrisbednarski  for the detailed analysis! SqsTransportMessage currently doesn't have an Id, I presume you're suggesting we add one - if we do, will it be duplicated as well?

**Comment by ahofman** [comment] 2017-04-24 04:06
On further thought - I'm not sure it even makes sense to use the Gateway when using SQS as your transport. Given two endpoints at separated sites, site A could simply bus.Send to an endpoint at site B, as long as both site A and site B can see Amazon SQS (which is all HTTPS under the hood anyway - same as the Gateway).

Is it possible for you to refactor to not use the Gateway in this scenario?

A (bad) workaround would be to simply not delete the message from S3 when it is received - it will then be aged out by the lifecycle policy when the TTL of the message expires. I'd rather avoid this though, as it would mean a lot more storage cost.

**Comment by ahofman** [comment] 2017-05-28 02:45
After a call with @chrisbednarski it's now clear that he needs to use the gateway to marshal between transports in NSB 4 - Site A is MSMQ and Site B is SQS. 

We agree that the root cause of the issue is that message ids are not globally unique when using the gateway. 

A workaround is to make multiple calls to SendToSites, one for each site. This will ensure that each message has a new id. I will document this and then close the issue.

**Comment by mauroservienti** [comment] 2019-05-14 13:29
Closing as with newer version of the transport we don't delete the payload anymore from S3 but we just let it expire.

**Closed by mauroservienti** 2019-05-14 13:29 UTC
