### ISSUE TITLE
SQS Transport limits native integration options by assuming message body is a Base64 encoded string

### ISSUE THREAD

**Issue by mauroservienti** [Particular/NServiceBus.AmazonSQS#1579] opened 2022-09-10 09:39 UTC
The transport, both in the V7 https://github.com/Particular/NServiceBus.AmazonSQS/blob/fb1a422e45d724a8e6ba55b9f82cf6448aced600/src/NServiceBus.Transport.SQS/Extensions/MessageExtensions.cs#L14-L22

and V8 https://github.com/Particular/NServiceBus.AmazonSQS/blob/6c95b644601a8f735ad441ba9dadbc3bfaf2e96c/src/NServiceBus.Transport.SQS/Extensions/MessageExtensions.cs#L13-L19

assumes the message body is a Base64 encoded string. When doing native integration, that's not necessarily the case.

**Comment by timbussmann** [comment] 2022-09-12 07:01
is this essentially a duplicate of https://github.com/Particular/NServiceBus.AmazonSQS/issues/1446?

**Comment by mauroservienti** [comment] 2022-09-12 07:03
Oh, yes. Good catch. Closing as duplicate of #1446

**Closed** 2022-09-12 07:04 UTC
