### ISSUE TITLE
Is it possible to send messages to endpoints in a different region?

### ISSUE THREAD

**Issue by biddlem** [Particular/NServiceBus.AmazonSQS#433] opened 2020-04-03 20:32 UTC
Scenario:

Endpoint A is hosted in us-west-2.  It wants to subscribe to events coming from an SQS queue for a service hosted in us-east-1. 

Is that possible out of the box?

Seems like my options are to either

1. Wait for the SNS support
2. Wire up an NServicebus router to faciliate the cross-region communication

**Comment by danielmarbach** [comment] 2020-04-06 11:16
Hi

It is possible to pull this off without SNS support or involving the router but it is very involved. I pushed up a quick spike to https://github.com/danielmarbach/SqsCrossRegion which shows some of the moving parts. Essentially the publisher and the subscriber would need to have a decorating client that knows how to forward certain types of request to the other region (the sample only shows the subscriber side). With that the subscription messages can be sent into the other region and then will be stored into the subscription storage of the publisher. When the publisher publishes similar logic would need to make sure to send messages to the subscriber in the other region. The problem is that subscriptions are stored with the endpoint name only not containing any indicator whether the other region is involved. See for example

![image](https://user-images.githubusercontent.com/174258/78552033-0dcf1200-7807-11ea-8c6a-40406f187f49.png)

So the publisher would need to assume that certain subscriber names are uniquely identifiable to a given region or if that is not possible the subscription messages would need to be tweaked to modify the subscriber address payload with something that indicates the special cases. For example something like

![image](https://user-images.githubusercontent.com/174258/78552909-a4e89980-7808-11ea-86f6-c5e6a8be51d5.png)

That being said I would wait for SNS support or use the router for now because getting all the details right with the approach I showed might be tricky

**Comment by VladimirMakaev** [comment] 2020-05-27 17:31
@danielmarbach 

We also experience a sort of a similar problem but also in the context of different account. Since we have different subsystems deployed in different AWS accounts. 

So EndpointA (account1) wants to send a command or generic message to EndpointB(account2)

SNS will work for the Publish and events but not for Send where recipient is direct.
In order for this to work we had to hack AmazonSqsClient with an overriden implementation of GetQueueUrl that passes QueueOwnerAWSAccountId

Can you implement something clean in the framework to make such Routing possible?

**Comment by danielmarbach** [comment] 2020-05-28 15:56
@VladimirMakaev to clarify are you asking if we could add support command routing over SNS?

Or about cross account sends with SQS?

**Comment by VladimirMakaev** [comment] 2020-05-28 16:12
Not really. But rather routing to another account for SQS queue directly. (assuming cross iam roles are setup)

e.g. something like 
```
transport.Routing(typeof(ISpecificCommand), "endpoint-b", ownerAwsAccountId = "234234324")
```

**Comment by danielmarbach** [comment] 2020-06-02 09:35
@VladimirMakaev I think this feature request makes total sense and I'd agree it is something worth considering especially because at this stage you have to go through the awkwardness of decorating the SQS Client.  

I've raised https://github.com/Particular/NServiceBus.AmazonSQS/issues/496 which can be picked up by the next enhancement release

Closing this for now.

**Closed by danielmarbach** 2020-06-02 09:35 UTC

**Comment by paulsiersma** [comment] 2022-06-16 12:59
@VladimirMakaev sorry to ressurect such an old thread but I'm also trying to set up cross-AWS-account endpoint communication, so far without luck. 

> SNS will work for the Publish and events

Are you saying it's possible out of the box for Events? Could you please elaborate on how you set this up? You would make me very happy.

**Comment by VladimirMakaev** [comment] 2022-06-16 13:34
@paulsiersma I don't really remember much as it was 2 years ago. But I think NSB will publish an event to SNS and at AWS level you can setup SNS to fanout to an SQS queue in any account which would then have a receiving NSB endpoint attached to it. (Given you sort out all cross account IAM roles accordingly)
